///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String a = 'assets/icons/A.java';
  static const String appIcon = 'assets/icons/app_icon.jpg';
  static const String appLogo = 'assets/icons/app_logo.png';
  static const String arrowLeft = 'assets/icons/arrow_left.svg';
  static const String arrowRight = 'assets/icons/arrow_right.svg';
  static const String arrowRightIos = 'assets/icons/arrow_right_ios.svg';
  static const String attendance = 'assets/icons/attendance.svg';
  static const String attendanceActive = 'assets/icons/attendance_active.svg';
  static const String back = 'assets/icons/back.svg';
  static const String calendar = 'assets/icons/calendar.svg';
  static const String came = 'assets/icons/came.svg';
  static const String clock = 'assets/icons/clock.svg';
  static const String clock1 = 'assets/icons/clock1.svg';
  static const String confirmRedNotificationIcon = 'assets/icons/confirm_red_notification_icon.svg';
  static const String emptyAttendance = 'assets/icons/empty_attendance.png';
  static const String emptyNotification = 'assets/icons/empty_notification.png';
  static const String emptyReport = 'assets/icons/empty_report.png';
  static const String flagRu = 'assets/icons/flag_ru.svg';
  static const String flagUz = 'assets/icons/flag_uz.svg';
  static const String gone = 'assets/icons/gone.svg';
  static const String home = 'assets/icons/home.svg';
  static const String homeActive = 'assets/icons/home_active.svg';
  static const String icRoundWarning = 'assets/icons/ic_round-warning.svg';
  static const String language = 'assets/icons/language.svg';
  static const String lock = 'assets/icons/lock.svg';
  static const String lockLogo = 'assets/icons/lock_logo.svg';
  static const String logosTelegram = 'assets/icons/logos_telegram.svg';
  static const String logout = 'assets/icons/logout.svg';
  static const String logout1 = 'assets/icons/logout1.svg';
  static const String logoutConfirmation = 'assets/icons/logout_confirmation.svg';
  static const String notification = 'assets/icons/notification.svg';
  static const String notification1 = 'assets/icons/notification1.svg';
  static const String passwordUnvisible = 'assets/icons/password_unvisible.svg';
  static const String passwordVisible = 'assets/icons/password_visible.svg';
  static const String permissions = 'assets/icons/permissions.svg';
  static const String phone = 'assets/icons/phone.svg';
  static const String profile = 'assets/icons/profile.svg';
  static const String profileActive = 'assets/icons/profile_active.svg';
  static const String profileInfo = 'assets/icons/profile_info.svg';
  static const String reminder = 'assets/icons/reminder.svg';
  static const String report = 'assets/icons/report.svg';
  static const String reportActive = 'assets/icons/report_active.svg';
  static const String rocket3 = 'assets/icons/rocket_3_.png';
  static const String ruRU = 'assets/translations/ru-RU.json';
  static const String splash = 'assets/icons/splash.png';
  static const String taskEmpty = 'assets/icons/task_empty.png';
  static const String upload = 'assets/icons/upload.svg';
  static const String uzCyrl = 'assets/translations/uz-Cyrl.json';
  static const String uzUZ = 'assets/translations/uz-UZ.json';
  static const String workSchedule = 'assets/icons/work_schedule.svg';
  static const String workScheduleActive = 'assets/icons/work_schedule_active.svg';

}
